ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS owner_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS support_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS brand_label TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_domain TEXT NOT NULL DEFAULT '';
