ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS logo_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email_from_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email_reply_to TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email_footer TEXT NOT NULL DEFAULT '';
